spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username:  pomaprokhorovich583@gmail.com
    password: xzxaxjqwxvwcncyg
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

library:
  maxDays: 30
  fine: 0.03
  daysBeforeLargerFine: 15
  largerFineFactor: 2.0

jwt:
  lifetime : 30m
  secret: 14u489ue983w99jmvut9843hgiosdiooijuioju2398u78oiuhfuihy88hidsosoososiojf9vm490ishiuvhnt4e89v9woihnio4v899092903ivnjiu4yhv895nnciuoi8rhn